NotifiError STAGE -> MAIN (#953)
* MVP-6758: Add back missing payload errors to SDK mutation schema (#952)

* MVP-6759: Implement NotifiError abstraction to handle Payload errors  (#954)

* MVP-6759:  implement NotifiError abstraction

* MVP-6579: export NotifiError module

* MVP-6579: add NotifiError unit tests

* MVP-6579: Optimize Github Action CI test process

* MVP-6760: Implement NotifiError in frontend-client (#955)

* MVP-6760: add throwIfPayloadError helper to NotifiError

* MVP-6760: integrate payload error handling in auth mutations

* MVP-6760: integrate payload error handling in client mutations

* MVP-6761: [notifi-react] Categorize error case using NotifiError (minimal changes)   (#956)

* MVP-6761: use NotifiError.from() for type-safe error handling

* MVP-6761: optimize: refactor(notifi-react): unify error handling with NotifiError.from()

* Fix unit / component test error

* MVP-6762: Doc (#957)

diff --git a/.github/workflows/unitest.yml b/.github/workflows/unitest.yml
--- a/.github/workflows/unitest.yml
+++ b/.github/workflows/unitest.yml
@@ -34,6 +34,8 @@ jobs:
         run: npm run build
 
       - name: Run tests - @notifi-network/notifi-node
+        id: test-notifi-node
+        continue-on-error: true
         run: npm run test:node
         env:
           FUSION_EVENT_ID: ${{ secrets.FUSION_EVENT_ID }}
@@ -41,4 +43,14 @@ jobs:
           TENANT_SID: ${{ secrets.TENANT_SID }}
 
       - name: Run tests - @notifi-network/notifi-frontend-client
+        id: test-notifi-frontend-client
+        continue-on-error: true
         run: npm run test:frontend-client
+
+      - name: Check all test results
+        if: always()
+        run: |
+          if [ "${{ steps.test-notifi-node.outcome }}" == "failure" ] || [ "${{ steps.test-notifi-frontend-client.outcome }}" == "failure" ]; then
+            echo "One or more tests failed"
+            exit 1
+          fi
